# Generated by Django 6.1.1 on 2026-09-29 05:08

import apps.presentation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Path to compressed, normalized video', upload_to=apps.presentation.models.video_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('raw_file_size', models.PositiveIntegerField(help_text='Original uploaded size in bytes (up to 250MB)')),
                ('compressed_file_size', models.PositiveIntegerField(default=0, help_text='Compressed size in bytes (<50MB)')),
                ('file_type', models.CharField(max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded (Staged)'), ('COMPRESSING', 'Compressing Video'), ('READY_FOR_ANALYSIS', 'Ready for Analysis'), ('PROCESSING_SPEECH', 'Processing Speech Analysis'), ('PROCESSING_VISION', 'Processing Behavioral Analysis'), ('SCORING', 'Calculating Scores'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presentation Video',
                'verbose_name_plural': 'Presentation Videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
