# Generated by Django 6.1.1 on 2026-09-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True, default='')),
                ('words_per_minute', models.FloatField(default=0.0)),
                ('filler_word_count', models.PositiveIntegerField(default=0)),
                ('filler_words_breakdown', models.JSONField(blank=True, default=dict)),
                ('clarity_score', models.PositiveIntegerField(default=80)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analysis', to='presentation.presentationvideo')),
            ],
            options={
                'verbose_name': 'Speech Analysis',
                'verbose_name_plural': 'Speech Analyses',
                'ordering': ['-processed_at'],
            },
        ),
    ]
