# Generated by Django 6.1.1 on 2026-09-29 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_speechanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_contact_score', models.PositiveIntegerField(default=75, help_text='Eye contact score 0-100 (% frames looking at camera)')),
                ('posture_score', models.PositiveIntegerField(default=80, help_text='Posture alignment score 0-100 (upright vs slouched/tilted)')),
                ('engagement_score', models.PositiveIntegerField(default=75, help_text='Facial engagement score 0-100 (attentiveness & positivity)')),
                ('frame_metrics', models.JSONField(blank=True, default=dict, help_text='Sampled metrics across frames (eye contact, posture, engagement signals)')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_analysis', to='presentation.presentationvideo')),
            ],
            options={
                'verbose_name': 'Behavioral Analysis',
                'verbose_name_plural': 'Behavioral Analyses',
                'ordering': ['-processed_at'],
            },
        ),
    ]
