# Generated by Django 6.1.1 on 2026-09-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_behavioralanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(default=0, help_text='Calculated composite score 0-100')),
                ('speech_score', models.PositiveIntegerField(default=0, help_text='Composite speech score 0-100 (pace + filler)')),
                ('behavioral_score', models.PositiveIntegerField(default=0, help_text='Composite behavioral score 0-100 (eye contact + posture + engagement)')),
                ('pace_score', models.PositiveIntegerField(default=0, help_text='Pacing subscore (optimal 130-160 WPM)')),
                ('filler_score', models.PositiveIntegerField(default=0, help_text='Filler word control subscore')),
                ('eye_contact_score', models.PositiveIntegerField(default=0, help_text='Camera gaze adherence subscore')),
                ('posture_score', models.PositiveIntegerField(default=0, help_text='Shoulder alignment and stability subscore')),
                ('engagement_score', models.PositiveIntegerField(default=0, help_text='Facial expressiveness and attentiveness subscore')),
                ('has_behavioral_data', models.BooleanField(default=True, help_text='Whether video had valid computer vision landmarks')),
                ('notes', models.TextField(blank=True, default='', help_text='Evaluation notes or degradation indicators')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_score', to='presentation.presentationvideo')),
            ],
            options={
                'verbose_name': 'Presentation Score',
                'verbose_name_plural': 'Presentation Scores',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
