# Generated by Django 6.1.1 on 2026-09-30 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_presentationscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='2-sentence encouraging executive evaluation')),
                ('strengths', models.JSONField(default=list, help_text='List of quantitative and qualitative presentation strengths')),
                ('improvements', models.JSONField(default=list, help_text='List of improvement objects containing category, observation, and actionable_drill')),
                ('practice_tip', models.TextField(blank=True, default='', help_text='Intentional phrasing and pacing sample sentence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedback', to='presentation.presentationvideo')),
            ],
            options={
                'verbose_name': 'Presentation Feedback',
                'verbose_name_plural': 'Presentation Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
