# Generated by Django 6.1.1 on 2026-09-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0005_presentationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationvideo',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded (Staged)'), ('COMPRESSING', 'Compressing Video'), ('READY_FOR_ANALYSIS', 'Ready for Analysis'), ('PROCESSING_SPEECH', 'Processing Speech Analysis'), ('PROCESSING_VISION', 'Processing Behavioral Analysis'), ('SCORING', 'Calculating Scores'), ('RETRYING', 'Retrying Analysis'), ('PARTIALLY_COMPLETED', 'Partially Completed'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=30),
        ),
        migrations.CreateModel(
            name='PipelineExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('AUDIO_EXTRACTION', 'Audio Extraction'), ('SPEECH_ANALYSIS', 'Speech Analysis (Whisper)'), ('VISION_ANALYSIS', 'Behavioral Analysis (MediaPipe)'), ('SCORING', 'Composite Scoring'), ('SUGGESTIONS', 'AI Coaching Suggestions'), ('PIPELINE', 'Full Pipeline')], max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('RETRY', 'Retrying'), ('DEGRADED', 'Gracefully Degraded'), ('FAILED', 'Failed')], max_length=20)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='presentation.presentationvideo')),
            ],
            options={
                'verbose_name': 'Pipeline Execution Log',
                'verbose_name_plural': 'Pipeline Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
