# Generated by Django 6.1.1 on 2026-09-23 06:13

import apps.cv.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Path to stored CV document', upload_to=apps.cv.models.cv_upload_to)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by candidate', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='Document format extension (pdf or docx)', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True if this is the active CV version used for scoring and matching')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Candidate who owns this CV', on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careerflow_candidate_cvs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='careerflow__user_id_fed942_idx'), models.Index(fields=['uploaded_at'], name='careerflow__uploade_55fa13_idx')],
            },
        ),
    ]
