# Generated by Django 6.1.1 on 2026-09-23 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Extracted text from the CV document')),
                ('skills', models.JSONField(default=list, help_text='List of extracted skills [React, Python, ...]')),
                ('education', models.JSONField(default=list, help_text='[{degree, institution, year}]')),
                ('experience', models.JSONField(default=list, help_text='[{title, company, duration_years}]')),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.OneToOneField(help_text='Candidate CV document associated with this parsed data', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='cv.candidatecv')),
            ],
            options={
                'db_table': 'careerflow_parsed_cvs',
                'ordering': ['-parsed_at'],
            },
        ),
    ]
