# Generated by Django 6.1.1 on 2026-09-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_parsedcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(help_text='Calculated score 0-100')),
                ('formatting_score', models.PositiveIntegerField(default=80, help_text='Formatting and completeness score (0-100)')),
                ('clarity_score', models.PositiveIntegerField(default=80, help_text='Clarity and impact score (0-100)')),
                ('keyword_strength_score', models.PositiveIntegerField(default=80, help_text='Keyword and action verb strength score (0-100)')),
                ('experience_score', models.PositiveIntegerField(default=80, help_text='Experience fit and details score (0-100)')),
                ('education_score', models.PositiveIntegerField(default=80, help_text='Education fit score (0-100)')),
                ('suggestions', models.JSONField(default=list, help_text="3 actionable edits e.g. ['Quantify checkout result', ...]")),
                ('signal_breakdown', models.JSONField(default=dict, help_text='Granular score breakdown and extracted signal metrics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.OneToOneField(help_text='Candidate CV document associated with this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='cv.candidatecv')),
            ],
            options={
                'db_table': 'careerflow_cv_feedback',
                'ordering': ['-updated_at'],
            },
        ),
    ]
