# Generated by Django 6.1.1 on 2026-09-23 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cvfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job role title e.g. Senior Frontend Engineer', max_length=255)),
                ('company', models.CharField(default='CareerFlow Client', help_text='Target hiring company', max_length=255)),
                ('role_type', models.CharField(blank=True, default='', help_text='Role category/seniority', max_length=255)),
                ('description', models.TextField(help_text='Detailed job description and responsibilities')),
                ('required_skills', models.JSONField(default=list, help_text="List of mandatory/preferred skills e.g. ['React', 'Python']")),
                ('threshold_score', models.PositiveIntegerField(default=75, help_text='Minimum score threshold for shortlisting (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='HR manager who posted or created this job brief', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careerflow_job_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title evaluated against', max_length=255)),
                ('company', models.CharField(default='CareerFlow Client', help_text='Company name', max_length=255)),
                ('job_description', models.TextField(blank=True, default='', help_text='Job description text evaluated')),
                ('match_score', models.PositiveIntegerField(help_text='Overall semantic similarity score (0-100)')),
                ('keyword_coverage', models.PositiveIntegerField(default=0, help_text='Percentage of required skills & keywords covered (0-100)')),
                ('category_scores', models.JSONField(default=dict, help_text="Sub-signal category breakdown e.g. {'domain_craft': 91, 'collaboration': 86, 'leadership': 74, 'accessibility': 62}")),
                ('skills_matched', models.JSONField(default=list, help_text='List of skills present in both CV and Job')),
                ('skills_missing', models.JSONField(default=list, help_text='List of required job skills missing from CV')),
                ('strengths', models.JSONField(default=list, help_text='Key matching strengths identified')),
                ('gaps', models.JSONField(default=list, help_text='Areas needing enhancement for this role')),
                ('recommendations', models.JSONField(default=list, help_text='Actionable suggestions to improve role match score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(help_text='Candidate CV evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='cv.candidatecv')),
                ('job', models.ForeignKey(blank=True, help_text='Associated job requirement brief if matching against a predefined job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='cv.jobrequirement')),
            ],
            options={
                'db_table': 'careerflow_cv_job_matches',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['cv', '-updated_at'], name='careerflow__cv_id_953a53_idx'), models.Index(fields=['match_score'], name='careerflow__match_s_554693_idx')],
            },
        ),
    ]
