# Generated by Django 6.1.1 on 2026-10-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title for the recruitment opening', max_length=200)),
                ('company_name', models.CharField(help_text='Hiring company or department organization', max_length=200)),
                ('department', models.CharField(blank=True, default='', help_text='Optional department or team', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed job description and responsibilities')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CLOSED', 'Closed')], default='ACTIVE', help_text='Current operational status of the room', max_length=20)),
                ('requirements_text', models.TextField(blank=True, default='', help_text='Detailed job requirements text criteria')),
                ('skills_required', models.JSONField(blank=True, default=list, help_text='List of required skills and proficiency requirements')),
                ('cv_weight', models.PositiveSmallIntegerField(default=50, help_text='Percentage weight allocated to CV match score (0-100)')),
                ('video_weight', models.PositiveSmallIntegerField(default=50, help_text='Percentage weight allocated to Video presentation score (0-100)')),
                ('share_token', models.CharField(blank=True, help_text='Cryptographically secure unique token for the public application link', max_length=64, null=True, unique=True)),
                ('link_is_active', models.BooleanField(default=True, help_text='Whether candidates can access the application page via share_token')),
                ('link_expires_at', models.DateTimeField(blank=True, help_text='Optional expiration timestamp for the shareable link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='HR Manager who created and owns this room', on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careerflow_recruitment_rooms',
                'ordering': ['-created_at'],
            },
        ),
    ]
