# Generated by Django 6.1.1 on 2026-10-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentroom',
            name='experience_level',
            field=models.CharField(choices=[('ENTRY', 'Entry Level (0-2 years)'), ('MID', 'Mid Level (2-5 years)'), ('SENIOR', 'Senior Level (5-8 years)'), ('LEAD', 'Lead / Principal (8+ years)')], default='MID', help_text='Target seniority or experience level required for the position', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitmentroom',
            name='role_category',
            field=models.CharField(blank=True, default='Engineering', help_text='Job role category (e.g. Engineering, Design, Product, Data)', max_length=100),
        ),
    ]
