# Generated by Django 6.1.1 on 2026-10-07 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_recruitmentroom_experience_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recruitmentroom',
            constraint=models.CheckConstraint(condition=models.Q(('cv_weight__gte', 0), ('cv_weight__lte', 100), ('video_weight__gte', 0), ('video_weight__lte', 100)), name='check_recruitment_room_weights_range'),
        ),
    ]
